ingester:
  replicas: 1
  resources:
    requests: { cpu: 25m, memory: 128Mi }
    limits: { cpu: 50m, memory: 256Mi }

distributor:
  replicas: 1
  resources:
    requests: { cpu: 25m, memory: 64Mi }
    limits: { cpu: 50m, memory: 128Mi }

querier:
  replicas: 1
  resources:
    requests: { cpu: 25m, memory: 64Mi }
    limits: { cpu: 50m, memory: 128Mi }

queryFrontend:
  replicas: 1
  resources:
    requests: { cpu: 25m, memory: 32Mi }
    limits: { cpu: 50m, memory: 64Mi }

gateway:
  replicas: 1
  resources:
    requests: { cpu: 25m, memory: 32Mi }
    limits: { cpu: 50m, memory: 64Mi }

compactor:
  replicas: 1
  resources:
    requests: { cpu: 25m, memory: 32Mi }
    limits: { cpu: 50m, memory: 64Mi }