apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
data:
  admin-user: YWRtaW4=      # base64 for "admin"
  admin-password: YWRtaW4=  # base64 for "admin"