deploymentMode: SingleBinary

singleBinary:
  resources:
    requests: { cpu: 25m, memory: 64Mi }
    limits: { cpu: 50m, memory: 128Mi }

loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

gateway:
  resources:
    requests: { cpu: 25m, memory: 32Mi }
    limits: { cpu: 50m, memory: 64Mi }

minio:
  enabled: true
  persistence:
    size: 5Gi
  resources:
    requests: { cpu: 50m, memory: 128Mi }
    limits: { cpu: 100m, memory: 256Mi }

lokiCanary:
  resources:
    requests: { cpu: 20m, memory: 24Mi }
    limits: { cpu: 40m, memory: 32Mi }

chunksCache:
  enabled: false
resultsCache:
  enabled: false
