logging:
  level:
    com.example.cart.services.cart_service: DEBUG

spring:
  lifecycle:
    timeout-per-shutdown-phase: 0s  # allow faster shutdown for tests
  grpc:
    server:
      enabled: false
