server:
  port: ${CART_SVC_API_PORT:8081}

logging:
  level:
    io.grpc: ERROR
    org.springframework.kafka: OFF
    org.apache.kafka: OFF
    io.lettuce.core: OFF
    io.opentelemetry.exporter: OFF
    io.opentelemetry.exporter.internal.http.HttpExporter: OFF
    com.github.loki4j: OFF

order-processing-system:
  messaging:
    cart-update-requests:
      topic-name: "cart-update-requests"
      topic-partitions: "0"

  handlers:
    cart-update-requests:
      timeout-sec: 15
      wait-sec: 10

spring:
  application:
    name: cart-service
  grpc:
    server:
      port: ${CART_SVC_GRPC_PORT:9091}
      ssl:
        secure: false
    client:
      channels:
        inventory-service:
          address: ${INVENTORY_SVC_HOST:inventory-service}:${INVENTORY_SVC_GRPC_PORT:9090}
          plaintext: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka-broker}:${KAFKA_PORT:9092}
    admin:
      auto-create: false
    listener:
      ack-mode: manual
    consumer:
      group-id: ${HOSTNAME:cart-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  tracing: { enabled: false }
  otlp:
    tracing:
      endpoint: ${TEMPO_PUSH_API_ENDPOINT:http://tempo-distributor:4318/v1/traces}
    metrics:
      export: { enabled: false }
