spring:
  application:
    name: cart

  config:
    import: configserver:${CENTRALIZED_CONFIG_SERVER_URL:http://centralized-config:8888}

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    prometheus:
      enabled: true

  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TRACING_ENDPOINT:http://alloy:4318/v1/traces}
    metrics:
      export:
        enabled: false