apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: app
  labels:
    app.kubernetes.io/name: cart-service
spec:
  selector:
    app.kubernetes.io/name: cart-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: app
  labels:
    app.kubernetes.io/name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cart-service
  template:
    metadata:
      namespace: app
      labels:
        app.kubernetes.io/name: cart-service
    spec:
      containers:
      - name: cart-service
        image: order-processing-system/cart-service:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 1
            memory: 384Mi
          limits:
            cpu: 1
            memory: 512Mi
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: env-common
