apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: app
  labels:
    app.kubernetes.io/name: inventory-service
spec:
  selector:
    app.kubernetes.io/name: inventory-service
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: app
  labels:
    app.kubernetes.io/name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-service
  template:
    metadata:
      namespace: app
      labels:
        app.kubernetes.io/name: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: order-processing-system/inventory-service:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
          limits:
            cpu: 200m
            memory: 512Mi
        ports:
          - containerPort: 9090
        envFrom:
          - configMapRef:
              name: env-common
