{
 "title": "Cart Service Performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "logs_search", "label": "Search Logs" },
   {
    "name": "endpoint",
    "label": "API Endpoint",
    "query": {
     "query": "label_values(traces_spanmetrics_latency_bucket{span_name=~\"^http.*\"},span_name)"
    }
   },
   {
    "name": "repo",
    "label": "Repository",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total,repository_name)"
    }
   },
   {
    "name": "repo_span_name",
    "label": "Repository Operation",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{repository_name=\"$repo\"},span_name)"
    }
   },
   {
    "name": "grpc_service",
    "label": "GRPC Service",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{rpc_system=\"grpc\"},rpc_service)"
    }
   },
   {
    "name": "grpc_span_name",
    "label": "GRPC Service Operation",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{rpc_service=\"$grpc_service\"},span_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"app\", container=\"cart-service\"})\r\n/\r\nsum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"app\", container=\"cart-service\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{namespace=\"app\", container=\"cart-service\"})\r\n/\r\nsum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"app\", container=\"cart-service\", resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from requests)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"app\", container=\"cart-service\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"app\", container=\"cart-service\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilisation (from limits)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"app\", container=\"cart-service\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"app\", container=\"cart-service\", resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cart Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"cart-service\", level=~\"ERROR|INFO\"} |~ \"(?i)$logs_search\""
    }
   ]
  },
  { "title": "HTTP Endpoint Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Requests Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service, span_name) (traces_spanmetrics_calls_total{service=\"cart-service\", span_name=~\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service, span_name) (traces_spanmetrics_calls_total{\r\n        service=\"cart-service\", status=~\"4..|5..\", span_name=~\"$endpoint\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n    sum by (service, span_name) (rate(traces_spanmetrics_calls_total{\r\n        service=\"cart-service\", span_name=~\"$endpoint\", status=~\"4..|5..\"}[5m]))\r\n    /\r\n    sum by (service, span_name) (rate(traces_spanmetrics_calls_total{\r\n        service=\"cart-service\", span_name=~\"$endpoint\"}[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Per Second (by endpoints)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (span_name) (\r\n  rate(traces_spanmetrics_calls_total{service=\"cart-service\", span_name=~\"$endpoint\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Latency (by endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, \r\n    sum by (service, span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", span_name=~\"$endpoint\"}[5m]))\r\n) * 1000",
     "legendFormat": "P5 - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.5, \r\n    sum by (service, span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", span_name=~\"$endpoint\"}[5m]))\r\n) * 1000",
     "legendFormat": "P50 - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.75, \r\n    sum by (service, span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", span_name=~\"$endpoint\"}[5m]))\r\n) * 1000",
     "legendFormat": "P75 - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, \r\n    sum by (service, span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", span_name=~\"$endpoint\"}[5m]))\r\n) * 1000",
     "legendFormat": "P95 - {{span_name}}"
    }
   ]
  },
  { "title": "Repository Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Repository Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (db_system, span_name) (rate(traces_spanmetrics_calls_total{service=\"cart-service\", repository_name=~\"$repo\"}[1m]))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "Repository Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, \r\n    sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", repository_name=~\"$repo\", span_name=~\"$repo_span_name\"}[1m]))\r\n) * 1000",
     "legendFormat": "P5 - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.5, \r\n    sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", repository_name=~\"$repo\", span_name=~\"$repo_span_name\"}[1m]))\r\n) * 1000",
     "legendFormat": "P50 - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.75, \r\n    sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", repository_name=~\"$repo\", span_name=~\"$repo_span_name\"}[1m]))\r\n) * 1000",
     "legendFormat": "P75 - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, \r\n    sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", repository_name=~\"$repo\", span_name=~\"$repo_span_name\"}[1m]))\r\n) * 1000",
     "legendFormat": "P95 - {{span_name}}"
    }
   ]
  },
  { "title": "GRPC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "GRPC Service Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (rpc_service, span_name) (rate(traces_spanmetrics_calls_total{service=\"cart-service\", rpc_service=~\"$grpc_service\"}[1m]))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  {
   "title": "GRPC Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.05, \r\n    sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", rpc_service=~\"$grpc_service\", span_name=~\"$grpc_span_name\"}[1m]))\r\n) * 1000",
     "legendFormat": "P5 - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.5, \r\n    sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", rpc_service=~\"$grpc_service\", span_name=~\"$grpc_span_name\"}[1m]))\r\n) * 1000",
     "legendFormat": "P50 - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.75, \r\n    sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", rpc_service=~\"$grpc_service\", span_name=~\"$grpc_span_name\"}[1m]))\r\n) * 1000",
     "legendFormat": "P75 - {{span_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, \r\n    sum by (span_name, le) (rate(traces_spanmetrics_latency_bucket{service=\"cart-service\", rpc_service=~\"$grpc_service\", span_name=~\"$grpc_span_name\"}[1m]))\r\n) * 1000",
     "legendFormat": "P95 - {{span_name}}"
    }
   ]
  }
 ]
}