order-processing-system:
  handlers:
    cart-update-requests:
      timeout-sec: 30

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/



