order-processing-system:
  handlers:
    cart-update-requests:
      timeout-sec: 300

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus

  observations:
    annotations:
      enabled: true

  tracing:
    enabled: true
    sampling:
      probability: 1

  otlp:
    tracing:
      endpoint: "http://alloy:4318/v1/traces"
      transport: http
