server:
  port: 8082

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  grpc:
    client:
      channels:
        inventory-service:
          address: ${INVENTORY_HOST:inventory}:${INVENTORY_GRPC_PORT:9091}
          plaintext: true
